### ISSUE TITLE
Issue with zroya module

### ISSUE THREAD

**Issue by agglomerator** [dunkmann00/Drive-Backup#5]
Don't know if you are supporting this still, but after the backup was done I got an error trying to import the "zroya" module.  I did a pip install and got another error.

### Here's the terminal output....
Starting Backup
Progress: [████████████████████] Files: 2204/2204 Folders: 202/202
Backup Complete! - Duration: 03:12:53
Traceback (most recent call last):
  File "D:\xxx\Python\google_drive_backup\google_drive_backup.py", line 615, in <module>
    main()
  File "D:\xxx\Python\google_drive_backup\google_drive_backup.py", line 598, in main
    import zroya
ModuleNotFoundError: No module named 'zroya'

### ****When I did a 'pip install zroya", I got this....****

PS D:\xxx\Python\google_drive_backup> pip install zroya
Collecting zroya
  Using cached zroya-0.2.4.tar.gz (26 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: zroya
  Building wheel for zroya (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for zroya (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\zroya
      copying zroya\dismiss_reason.py -> build\lib.win-amd64-cpython-311\zroya
      copying zroya\template_enums.py -> build\lib.win-amd64-cpython-311\zroya
      copying zroya\version.py -> build\lib.win-amd64-cpython-311\zroya
      copying zroya\__init__.py -> build\lib.win-amd64-cpython-311\zroya
      running build_ext
      building '_zroya' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\module
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I./module -IC:\Users\xxx\AppData\Local\Programs\Python\Python311\include -IC:\Users\xxx\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /EHsc /Tp./module\event_handler.cpp /Fobuild\temp.win-amd64-cpython-311\Release\./module\event_handler.obj
      event_handler.cpp
      C:\Users\xxx\AppData\Local\Temp\pip-install-2rt4clx7\zroya_5c42a2834c7f4e2a894becc948cb1af1\module\wintoastlib.h(3): fatal error C1083: Cannot open include file: 'Windows.h': No such file or directory

### **The backup finished, so is this error important?**

**Comment by dunkmann00** [comment]
Hi! No, that's not a big deal. The zroya module is used to show a notification letting you know the backup completed. So your backup completed successfully. 

I am currently trying to update this project and change how the notifications are handled. So thanks for bringing this issue to my attention.

**Comment by agglomerator** [comment]
Ok thanks for the reply.

Is there a way to provide a name and path for the logfile that is created?

Andre Kvaternik

**Comment by dunkmann00** [comment]
Not at the moment. But I will make sure to add that feature in the update.

**Comment by dunkmann00** [comment]
This should be all set with the new version. Both the issue with `zroya` and the option to provide a custom path for the logfile.

Thanks!
